#!/usr/bin/env bash
# Your Bash script must be 7 lines long or less
# There must be a new line at the end of the file
# You respect Bash script requirements
# You cannot use ;
# You cannot use &&
# You cannot use wget

chmod 644 /etc/nginx/nginx.conf
sed -Ei 's/\s*#?\s*user .*/user nginx;/' /etc/nginx/nginx.conf
sed -Ei 's/(listen (\[::\]:)?80) /\180 /' /etc/nginx/sites-enabled/default
pkill apache2
su nginx -s /bin/bash -c 'service nginx restart'
